# 应用程序配置文件，包含游戏区域坐标、模板匹配阈值、日志路径等配置。

REGIONS:
  # 区域坐标配置 (单位: 像素)
  playing_left: [[260, 346], [700, 446]]  # 左侧出牌区域
  playing_middle: [[425, 500], [970, 710]]  # 中间出牌区域
  playing_right: [[700, 346], [1140, 446]]  # 右侧出牌区域
  my_cards: [[350, 730], [1020, 820]]  # 中间我的手牌显示区域
  remaining_cards_left: [[20, 555], [85, 580]]  # 左边剩余牌数显示区域
  remaining_cards_middle: [[765, 900], [830, 930]]  # 中间剩余牌数显示区域
  remaining_cards_right: [[1310, 555], [1380, 580]]  # 右边剩余牌数显示区域
  three_displayed_cards: [[540, 120], [860, 140]]  # 游戏结束时上方三张底牌的显示区域

THRESHOLDS:
  # 模板匹配阈值
  card: 0.95  # 卡牌 匹配置信度阈值
  landlord: 0.95  # 地主标记 匹配置信度阈值
  end_game: 0.25  # 游戏结束 颜色占比阈值
  pass: 0.9  # 不出牌标记 匹配置信度阈值
  wait: 0.9  # 等待出牌 颜色占比阈值

# 间隔（秒）
SCREENSHOT_INTERVAL: 0.2  # 截图间隔
GUI_UPDATE_INTERVAL: 0.2  # 画面更新间隔
GAME_START_INTERVAL: 1  # 等待下一次判断游戏开始时的间隔

# 记牌器窗口默认显示位置坐标(OFFSET和CENTER二选一)
GUI_LOCATION:
  # "OFFSET_X": 0  # 左上角起始X坐标
  OFFSET_Y: 0  # 左上角起始Y坐标
  CENTER_X: 700  # 中心X坐标
  # "CENTER_Y": 0  # 中心Y坐标

# 其他参数
FONT_SIZE: 25  # 标签字体大小
LOG_LEVEL: DEBUG  # 日志记录级别（TRACE、DEBUG、INFO、SUCCESS、WARNING、ERROR、CRITICAL）
LOG_RETENTION: 3  # 日志保留数量
